# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Project\BridgeDetection\GroundStation\Version1\MainUI.ui'
#
# Created: Wed Apr 13 16:42:29 2016
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainFrom(object):
    def setupUi(self, MainFrom):
        MainFrom.setObjectName(_fromUtf8("MainFrom"))
        MainFrom.resize(1088, 791)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainFrom.sizePolicy().hasHeightForWidth())
        MainFrom.setSizePolicy(sizePolicy)
        MainFrom.setMinimumSize(QtCore.QSize(0, 0))
        MainFrom.setMaximumSize(QtCore.QSize(1088, 791))
        self.verticalLayoutWidget = QtGui.QWidget(MainFrom)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(531, 321, 551, 301))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.MiddleLayerRight = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.MiddleLayerRight.setMargin(5)
        self.MiddleLayerRight.setObjectName(_fromUtf8("MiddleLayerRight"))
        self.ImageTopicLable = QtGui.QLabel(self.verticalLayoutWidget)
        self.ImageTopicLable.setObjectName(_fromUtf8("ImageTopicLable"))
        self.MiddleLayerRight.addWidget(self.ImageTopicLable)
        self.ImageAddressField = QtGui.QPlainTextEdit(self.verticalLayoutWidget)
        self.ImageAddressField.setObjectName(_fromUtf8("ImageAddressField"))
        self.MiddleLayerRight.addWidget(self.ImageAddressField)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setMargin(10)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btnImageOpen = QtGui.QPushButton(self.verticalLayoutWidget)
        self.btnImageOpen.setObjectName(_fromUtf8("btnImageOpen"))
        self.horizontalLayout.addWidget(self.btnImageOpen)
        self.btnImageGenerate = QtGui.QPushButton(self.verticalLayoutWidget)
        self.btnImageGenerate.setObjectName(_fromUtf8("btnImageGenerate"))
        self.horizontalLayout.addWidget(self.btnImageGenerate)
        self.MiddleLayerRight.addLayout(self.horizontalLayout)
        self.SearchKeyWordField = QtGui.QPlainTextEdit(self.verticalLayoutWidget)
        self.SearchKeyWordField.setObjectName(_fromUtf8("SearchKeyWordField"))
        self.MiddleLayerRight.addWidget(self.SearchKeyWordField)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setMargin(10)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.btnImageSearch = QtGui.QPushButton(self.verticalLayoutWidget)
        self.btnImageSearch.setObjectName(_fromUtf8("btnImageSearch"))
        self.horizontalLayout_2.addWidget(self.btnImageSearch)
        self.MiddleLayerRight.addLayout(self.horizontalLayout_2)
        self.verticalLayoutWidget_2 = QtGui.QWidget(MainFrom)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 320, 511, 301))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.MiddleLayerLeft = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.MiddleLayerLeft.setMargin(0)
        self.MiddleLayerLeft.setObjectName(_fromUtf8("MiddleLayerLeft"))
        self.StatusTopicLabel = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.StatusTopicLabel.setObjectName(_fromUtf8("StatusTopicLabel"))
        self.MiddleLayerLeft.addWidget(self.StatusTopicLabel)
        self.StatusOutputField = QtGui.QTextEdit(self.verticalLayoutWidget_2)
        self.StatusOutputField.setObjectName(_fromUtf8("StatusOutputField"))
        self.MiddleLayerLeft.addWidget(self.StatusOutputField)
        self.verticalLayoutWidget_3 = QtGui.QWidget(MainFrom)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(11, 641, 1071, 141))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.WaypointTopicLable = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.WaypointTopicLable.setMinimumSize(QtCore.QSize(140, 40))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("SimSun-ExtB"))
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.WaypointTopicLable.setFont(font)
        self.WaypointTopicLable.setObjectName(_fromUtf8("WaypointTopicLable"))
        self.horizontalLayout_3.addWidget(self.WaypointTopicLable)
        self.xlable = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.xlable.setMinimumSize(QtCore.QSize(30, 41))
        self.xlable.setObjectName(_fromUtf8("xlable"))
        self.horizontalLayout_3.addWidget(self.xlable)
        self.xinput = QtGui.QLineEdit(self.verticalLayoutWidget_3)
        self.xinput.setObjectName(_fromUtf8("xinput"))
        self.horizontalLayout_3.addWidget(self.xinput)
        self.ylable = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.ylable.setMinimumSize(QtCore.QSize(18, 0))
        self.ylable.setObjectName(_fromUtf8("ylable"))
        self.horizontalLayout_3.addWidget(self.ylable)
        self.yinput = QtGui.QLineEdit(self.verticalLayoutWidget_3)
        self.yinput.setObjectName(_fromUtf8("yinput"))
        self.horizontalLayout_3.addWidget(self.yinput)
        self.zlable = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.zlable.setMinimumSize(QtCore.QSize(30, 0))
        self.zlable.setObjectName(_fromUtf8("zlable"))
        self.horizontalLayout_3.addWidget(self.zlable)
        self.zinput = QtGui.QLineEdit(self.verticalLayoutWidget_3)
        self.zinput.setObjectName(_fromUtf8("zinput"))
        self.horizontalLayout_3.addWidget(self.zinput)
        self.btnWaypointSend = QtGui.QPushButton(self.verticalLayoutWidget_3)
        self.btnWaypointSend.setObjectName(_fromUtf8("btnWaypointSend"))
        self.horizontalLayout_3.addWidget(self.btnWaypointSend)
        self.btnWaypointAccomplish = QtGui.QPushButton(self.verticalLayoutWidget_3)
        self.btnWaypointAccomplish.setObjectName(_fromUtf8("btnWaypointAccomplish"))
        self.horizontalLayout_3.addWidget(self.btnWaypointAccomplish)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.CameraTopicLable = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.CameraTopicLable.setMinimumSize(QtCore.QSize(140, 40))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("SimSun-ExtB"))
        font.setBold(True)
        font.setWeight(75)
        self.CameraTopicLable.setFont(font)
        self.CameraTopicLable.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.CameraTopicLable.setObjectName(_fromUtf8("CameraTopicLable"))
        self.horizontalLayout_4.addWidget(self.CameraTopicLable)
        self.anglelable = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.anglelable.setObjectName(_fromUtf8("anglelable"))
        self.horizontalLayout_4.addWidget(self.anglelable)
        self.angleinput = QtGui.QLineEdit(self.verticalLayoutWidget_3)
        self.angleinput.setObjectName(_fromUtf8("angleinput"))
        self.horizontalLayout_4.addWidget(self.angleinput)
        self.numlable = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.numlable.setObjectName(_fromUtf8("numlable"))
        self.horizontalLayout_4.addWidget(self.numlable)
        self.numinput = QtGui.QLineEdit(self.verticalLayoutWidget_3)
        self.numinput.setObjectName(_fromUtf8("numinput"))
        self.horizontalLayout_4.addWidget(self.numinput)
        self.locallable = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.locallable.setObjectName(_fromUtf8("locallable"))
        self.horizontalLayout_4.addWidget(self.locallable)
        self.localinput = QtGui.QLineEdit(self.verticalLayoutWidget_3)
        self.localinput.setObjectName(_fromUtf8("localinput"))
        self.horizontalLayout_4.addWidget(self.localinput)
        self.btnCameraPicture = QtGui.QPushButton(self.verticalLayoutWidget_3)
        self.btnCameraPicture.setObjectName(_fromUtf8("btnCameraPicture"))
        self.horizontalLayout_4.addWidget(self.btnCameraPicture)
        self.btnCameraVideo = QtGui.QPushButton(self.verticalLayoutWidget_3)
        self.btnCameraVideo.setObjectName(_fromUtf8("btnCameraVideo"))
        self.horizontalLayout_4.addWidget(self.btnCameraVideo)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(200)
        self.horizontalLayout_5.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_5.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.btnOpen3d = QtGui.QPushButton(self.verticalLayoutWidget_3)
        self.btnOpen3d.setObjectName(_fromUtf8("btnOpen3d"))
        self.horizontalLayout_5.addWidget(self.btnOpen3d)
        self.btnImport = QtGui.QPushButton(self.verticalLayoutWidget_3)
        self.btnImport.setObjectName(_fromUtf8("btnImport"))
        self.horizontalLayout_5.addWidget(self.btnImport)
        self.btnSetting = QtGui.QPushButton(self.verticalLayoutWidget_3)
        self.btnSetting.setObjectName(_fromUtf8("btnSetting"))
        self.horizontalLayout_5.addWidget(self.btnSetting)
        self.btnCheck = QtGui.QPushButton(self.verticalLayoutWidget_3)
        self.btnCheck.setObjectName(_fromUtf8("btnCheck"))
        self.horizontalLayout_5.addWidget(self.btnCheck)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayoutWidget_4 = QtGui.QWidget(MainFrom)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 1071, 301))
        self.verticalLayoutWidget_4.setObjectName(_fromUtf8("verticalLayoutWidget_4"))
        self.TopLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.TopLayout.setMargin(0)
        self.TopLayout.setObjectName(_fromUtf8("TopLayout"))
        self.ThreedTopicLabel = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.ThreedTopicLabel.setObjectName(_fromUtf8("ThreedTopicLabel"))
        self.TopLayout.addWidget(self.ThreedTopicLabel)
        self.ThreedViewField = QtGui.QGraphicsView(self.verticalLayoutWidget_4)
        self.ThreedViewField.setObjectName(_fromUtf8("ThreedViewField"))
        self.TopLayout.addWidget(self.ThreedViewField)

        self.retranslateUi(MainFrom)
        QtCore.QMetaObject.connectSlotsByName(MainFrom)

    def retranslateUi(self, MainFrom):
        MainFrom.setWindowTitle(_translate("MainFrom", "GroundStation", None))
        self.ImageTopicLable.setText(_translate("MainFrom", "ImageProcessingField", None))
        self.ImageAddressField.setPlainText(_translate("MainFrom", "This is the address of Image", None))
        self.btnImageOpen.setText(_translate("MainFrom", "OPEN", None))
        self.btnImageGenerate.setText(_translate("MainFrom", "GENERATE", None))
        self.SearchKeyWordField.setPlainText(_translate("MainFrom", "This is the Search keyword", None))
        self.btnImageSearch.setText(_translate("MainFrom", "SEARCH", None))
        self.StatusTopicLabel.setText(_translate("MainFrom", "Status Output Field", None))
        self.WaypointTopicLable.setText(_translate("MainFrom", "WAYPOINT SETTING:", None))
        self.xlable.setText(_translate("MainFrom", "X:", None))
        self.ylable.setText(_translate("MainFrom", "Y:", None))
        self.zlable.setText(_translate("MainFrom", "Z:", None))
        self.btnWaypointSend.setText(_translate("MainFrom", "SEND", None))
        self.btnWaypointAccomplish.setText(_translate("MainFrom", "ACCOMPLISH", None))
        self.CameraTopicLable.setText(_translate("MainFrom", "CAMERA   SETTING:", None))
        self.anglelable.setText(_translate("MainFrom", "ANGLE", None))
        self.numlable.setText(_translate("MainFrom", "NUM", None))
        self.locallable.setText(_translate("MainFrom", "LOCAL", None))
        self.btnCameraPicture.setText(_translate("MainFrom", "PICTURE", None))
        self.btnCameraVideo.setText(_translate("MainFrom", "VIDEO", None))
        self.btnOpen3d.setText(_translate("MainFrom", "OPEN3D", None))
        self.btnImport.setText(_translate("MainFrom", "IMPORT", None))
        self.btnSetting.setText(_translate("MainFrom", "SETTING", None))
        self.btnCheck.setText(_translate("MainFrom", "CHECK", None))
        self.ThreedTopicLabel.setText(_translate("MainFrom", "3D Image Field", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainFrom = QtGui.QWidget()
    ui = Ui_MainFrom()
    ui.setupUi(MainFrom)
    MainFrom.show()
    sys.exit(app.exec_())

